

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Sobre 
                <strong>Ratoncitos</strong>
            </h2>
            <hr>
        </div>
        <div class="col-md-6">
            <img class="img-responsive img-border-left" src="../img/slide-2.jpg" alt="">
        </div>
        <div class="col-md-6">
            <p>El centro infantil Ratoncitos comienza su andaduda en el curso 2012-2013 con un proposito principal, ofrecer a la familias, y sobre todo a los niños, un lugar doinde se sientan felices, seguros, queridos y atendidos en todos los aspectos.</p>
            <p>Por eso cuidamos todos los detalles de su educacion, cuidado y nutricion, para que nuestros alumnos y alumnas esten igual de bien atendidos que en casa.</p>
            <p>Nuestro personal está compuesto por un equipo de profesoras, tecnicos superiores y auxiliares en educacion infantil. Cualificados y seleccionados cuidadosamente, con la preparacion necesaria y exigida por el Ministerio de Educacion y Ciencia.</p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Nuestro
                <strong>Equipo</strong>
            </h2>
            <hr>
        </div>
        <div class="col-sm-4 text-center">
            <img class="img-responsive" src="../img/cambio.jpg" alt="">
            <!--h3>John Smith
                <small>Job Title</small>
            </h3-->
        </div>
        <div class="col-sm-4 text-center">
            <img class="img-responsive" src="../img/Niños-Escuelas-Infantiles.jpg" alt="">
            <!--h3>John Smith
                <small>Job Title</small>
            </h3-->
        </div>
        <div class="col-sm-4 text-center">
            <img class="img-responsive" src="../img/Comedor-escuela-epi-1-700-400.jpg" alt="">
            <!--h3>John Smith
                <small>Job Title</small>
            </h3-->
        </div>
        <div class="clearfix"></div>
    </div>
</div>
    
