

<?php include  '../app/parts/head.php'; ?>        

<!-- http://stackoverflow.com/questions/14071261/how-to-setup-a-404-page-in-phalcon -->
<div align="center"  style="background: rgba(255, 255, 255, 0.9) none repeat scroll 0 0;">
    <div>
        <strong>ERROR 500</strong>
        <br />
        <br />
        Error interno del sistema.
        <br />
        <br />
        Algo fue mal, si el error persiste por favor pongase en contacto con nosotros.
        <br />
        <br />
        ERROR
        <br />
    </div>
</div>
<br />

<?php include '../app/parts/foot.php'; ?>
