

<?php include  '../app/parts/head.php'; ?>        

<!-- http://stackoverflow.com/questions/14071261/how-to-setup-a-404-page-in-phalcon -->
<div align="center"  style="background: rgba(255, 255, 255, 0.9) none repeat scroll 0 0;">
    <div>
        <strong>ERROR 401</strong>
        <br />
        <br />
        Desautorizado.
        <br />
        <br />
        You don't have access to this option. Contact an administrator
        Usted no tiene acceso a esta opción. Por favor, contacte con el administrador.
        <br />
        <br />
        ERROR
        <br />
    </div>
</div>
<br />

<?php include '../app/parts/foot.php'; ?>
