


<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">situación de 
                <strong>Ratoncitos</strong>
            </h2>
            <hr>
        </div>
        <div class="col-md-8">
            <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
            <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=36.713804,-4.628123&amp;spn=36.713804,-4.628123&amp;t=m&amp;z=4&amp;output=embed"></iframe>

        </div>
        <div class="col-md-4">
            <p>Telefono:
                <strong>952 42 29 93</strong>
            </p>
            <p>Email:
                <strong><a href="mailto:samu@samu.com">samu@samu.com</a></strong>
            </p>
            <p>Dirección:
                <strong>Calle Dámaso Ruano, bajo 1
                    <br>29570 Cartama, Málaga</strong>
            </p>
            <p>Horario:
                <strong><br>Lunes a Viernes : 7:15 - 19:00
                    <br>Aula Matinal : 7:15 - 9:00
                    <br>Ludoteca : 17:00 - 19:00</strong>
            </p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">formulario de
                <strong>Contacto</strong>
            </h2>
            <hr>
            <p>Para contactar con nosotros, por favor rellene los siguientes campos y nos pondremos en contacto con usted lo antes posible.</p>
            <form role="form">
                <div class="row">
                    <div class="form-group col-lg-4">
                        <label>Nombre</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group col-lg-4">
                        <label>Dirección de Email</label>
                        <input type="email" class="form-control">
                    </div>
                    <div class="form-group col-lg-4">
                        <label>Número de Teléfono</label>
                        <input type="tel" class="form-control">
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group col-lg-12">
                        <label>Mensage</label>
                        <textarea class="form-control" rows="6"></textarea>
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="hidden" name="save" value="contact">
                        <button type="submit" class="btn btn-default">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
    
