


<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Blog de
                <strong>Ratoncitos</strong>
            </h2>
            <hr>
        </div>
        <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="../img/slide-1.jpg" alt="">
            <h2>Primer Post
                <br>
                <small>2 de Diciembre de 2015</small>
            </h2>
            <p>Empezamos con gran ilusion y ganas de emprender este nuevo proyecto que ha sido siempre nuestro mayor sueño. Estamos abiertos durante todo el año. Puede visitarnos y conocer nuestro centro cuando usted quiera, sin necesidad de pedir cita previa, de lunes a viernes, y le informaremos de todo lo que necesite saber.</p>
            <a href="#" class="btn btn-default btn-lg">Leer Más</a>
            <hr>
        </div>
        <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="../img/slide-2.jpg" alt="">
            <h2>Ingles
                <br>
                <small>3 de Diciembre de 2015</small>
            </h2>
            <p>A partir del primer año de vida de sus hijos, estaran en contacto con este idioma. A traves de material didactico y canciones, el personal cualificado hará que sus hijos se familiaricen con el ingles como segunda lengua.</p>
            <a href="#" class="btn btn-default btn-lg">Leer Más</a>
            <hr>
        </div>
        <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="../img/slide-3.jpg" alt="">
            <h2>Instalaciones
                <br>
                <small>4 de Diciembre de 2015</small>
            </h2>
            <p>Nuestras instalaciones estan dotadas con modernos sistemas de seguridad como: </p>
            <p>- Puestas pivotantes sin bisagras antipinzamiento.</p>
            <p>- Enchufes e interruptores elevados del suelo.</p>
            <p>- Zocalos de madera en todas las aulas y el comedor a modo de proteccion.</p>
            <p>- Esquineras acolchadas.</p>
            <p>- Patio de juegos protegidos con losetas de caucho de 4 cm para proteger y amortiguar las cidas.</p>
            <p>Y ademas todas nuestras aulas disponen de ventilacion y luz natural.</p>

            <p>El mobiliario es homologado y adaptado a cada etapa evolutiva del niño. Y todos nuestros juguetes cumplen con la normativa vigente.</p>
            <a href="#" class="btn btn-default btn-lg">Leer Más</a>
            <hr>
        </div>
        <div class="col-lg-12 text-center">
            <ul class="pager">
                <li class="previous"><a href="#">&larr; Antiguos</a>
                </li>
                <li class="next"><a href="#">Nuevos &rarr;</a>
                </li>
            </ul>
        </div>
    </div>
</div>
    
