

<div class="row">
    <div class="box">
        <div class="col-lg-12 text-center">
            <div id="carousel-example-generic" class="carousel slide">
                <!-- Indicators -->
                <ol class="carousel-indicators hidden-xs">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="img-responsive img-full" src="../img/slide-1.jpg" alt="">
                    </div>
                    <div class="item">
                        <img class="img-responsive img-full" src="../img/slide-2.jpg" alt="">
                    </div>
                    <div class="item">
                        <img class="img-responsive img-full" src="../img/slide-3.jpg" alt="">
                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="icon-next"></span>
                </a>
            </div>
            <h2 class="brand-before">
                <small>Bienvenidos a la Escuela Infantil </small>
            </h2>
            <h1 class="brand-name">RATONCITOS</h1>
            <hr class="tagline-divider">
            <h2>
                <small>por
                    <strong>Samu S.A.</strong>
                </small>
            </h2>
        </div>
    </div>
</div>

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">¿Qué es
                <strong>Ratoncitos</strong>
                ?
            </h2>
            <hr>
            <img class="img-responsive img-border img-left" src="../img/intro-pic.jpg" alt="">
            <hr class="visible-xs">
            <p>La Escuela Infantil "Ratoncitos" está gestionada por Cristina Pino Ramirez y está ubicada en la provincia de Málaga, en la localidad de Cártama. En nuestro centro proporcionamos a niños y niñas de primer ciclo de educacion infantil (0 a 3 años), un lugar educativo y pedagogico de alta calidad, atendidos por personal cualificado que planifican y supervisan el desarrollo de vuestros pequeños.</p>
            <p>El objetivo principal de nuestra escuela es conseguir que los niños se sientan felices y seguros de sí mismos, y para ello, hemos creado un entorno afectivo, que les hace desarrollarse plenamente. También queremos que los padres, al dejar a los niños en nuestro centro, se queden tranquilos, y vean en nuestra escuela una prolongacion del hogar.</p>
        </div>
    </div>
</div>

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Nuestra
                <strong>Filosofia</strong>
            </h2>
            <hr>
            <p>Trabajamos la atención temprana con un equipo de orientacion interdisciplinar para detectar precozmente posibles trastornos en el desarrollo del menor.</p>
            <p>Tambien complementamos los servicios con actividades de aprendizaje de talleres de dibujo y pintura, psicromotricidad gruesa y fina, baile, teatro, jornadas de cine, iniciacion a la musica, juegos de logica, bits de inteligencia y cuentacuentos.</p>
            <p>Hacemos a vuestros pequeños protagonistas y participes de todas la celebraciones y fiestas de nuestro entorno y ciudad.</p>
            <p>El juego infantil es esencial para su desarrollo, por ello seguimos de cerca ssu progresos, creamos estilos educativos basados en la confianza, cariño, optimosmo y firmeza que hacen de cada niño o niña que sea una persona unica e irrepetible.</p>
        </div>
    </div>
</div>

