
<!-- http://stackoverflow.com/questions/14071261/how-to-setup-a-404-page-in-phalcon -->
<div align="center">
    <div>
        <strong>ERROR 404</strong>
        <br />
        <br />
        Ha intentado acceder a una página que no existe o ha sido movida.
        <br />
        <br />
        Por favor, haga clic en los enlaces en la barra superior de navegación para desplazarse a otras partes del sitio o si desea ponerse en contacto con nosotros pulse en contacto.
        <br />
        <br />
        ERROR
    </div>
</div>

