

<div id="samu" align="center"  style="background: rgba(255, 255, 255, 0.9) none repeat scroll 0 0;">
  	<div>
		Zona de Trabajo
		
		<div id="dialogo_samu" title="Basic dialog">
	  	<P>
			samuel dentro
	  	</P>
		</div>
	
		<div id="dialog_samu" title="Basic dialog">
	  	<P>
			samuel fuera
	  	</P>
		</div>
	
		<?php echo Phalcon\Tag::submitButton(array("Open Dialog dentro", "id" => "opener_p")); ?>
		<?php echo Phalcon\Tag::submitButton(array("Open Dialog fuera", "id" => "opener_p2")); ?>
  	</div>


<!---------------------------------------------------------------->

  	<div id="products">
		<h1 class="ui-widget-header">Products</h1>
		<div id="catalog">
	  	<h2><a href="#">T-Shirts</a></h2>
	  	<div>
			<ul>
		  	<li class="samu">Lolcat Shirt</li>
		  	<li class="samu">Cheezeburger Shirt</li>
		  	<li class="samu">Buckit Shirt</li>
			</ul>
	  	</div>
	  	<h2><a href="#">Bags</a></h2>
	  	<div>
			<ul>
		  	<li class="samu">Zebra Striped</li>
		  	<li class="samu">Black Leather</li>
		  	<li class="samu">Alligator Leather</li>
			</ul>
	  	</div>
	  	<h2><a href="#">Gadgets</a></h2>
	  	<div>
			<ul>
		  	<li class="samu">iPhone</li>
		  	<li class="samu">iPod</li>
		  	<li class="samu">iPad</li>
			</ul>
	  	</div>
		</div>
  	</div>
	 	
  	<div id="cart">
		<h1 class="ui-widget-header">Shopping Cart</h1>
		<div class="ui-widget-content">
	  	<ol>
			<li class="placeholder">Add your items here</li>
	  	</ol>
		</div>
  	</div>
	

<!---------------------------------------------------------------->	
	
  	<div class="azul arrastrable">Samu Azul 1</div> 
  	<div class="rojo arrastrable">Samu Rojo 1</div> 
  	<div class="rojo arrastrable">Samu Rojo 2</div> 
  	<div class="azul arrastrable">Samu Azul 2</div> 
	
  	<div id="sueltarojo" class="suelta"> 
	 	Suelta aquí elementos rojos 
  	</div> 
  	<div id="sueltaazul" class="suelta"> 
	 	Suelta aquí elementos azules 
  	</div>
	
	
</div>

<br/>

   